export enum ScreenAction {
    FETCH_VIDEOS = "FETCH_VIDEOS",
    CHANGE_VIDEO = "CHANGE_VIDEO",
    UPDATE_SETTINGS = "UPDATE_SETTINGS",
    TOAST = "TOAST",
    SET_MESSAGE = "SET_MESSAGE",
    CLEAR_MESSAGE = "CLEAR_MESSAGE",
    TOGGLE_CONTROLS = "TOGGLE_CONTROLS",
    KILL_APP = "KILL_APP",
}